/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'
import { Route as BrandAnalysisIndexRouteImport } from './routes/brand-analysis/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as AgentStudioIndexRouteImport } from './routes/agent-studio/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdPerformanceIndexRouteImport } from './routes/ad-performance/index'
import { Route as CanvasIdRouteImport } from './routes/canvas/$id'
import { Route as AdminTemplateAddRouteImport } from './routes/admin/template.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/canvas/',
  path: '/canvas/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandAnalysisIndexRoute = BrandAnalysisIndexRouteImport.update({
  id: '/brand-analysis/',
  path: '/brand-analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentStudioIndexRoute = AgentStudioIndexRouteImport.update({
  id: '/agent-studio/',
  path: '/agent-studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdPerformanceIndexRoute = AdPerformanceIndexRouteImport.update({
  id: '/ad-performance/',
  path: '/ad-performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIdRoute = CanvasIdRouteImport.update({
  id: '/canvas/$id',
  path: '/canvas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplateAddRoute = AdminTemplateAddRouteImport.update({
  id: '/admin/template/add',
  path: '/admin/template/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/ad-performance': typeof AdPerformanceIndexRoute
  '/admin': typeof AdminIndexRoute
  '/agent-studio': typeof AgentStudioIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/brand-analysis': typeof BrandAnalysisIndexRoute
  '/canvas': typeof CanvasIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/admin/template/add': typeof AdminTemplateAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/ad-performance': typeof AdPerformanceIndexRoute
  '/admin': typeof AdminIndexRoute
  '/agent-studio': typeof AgentStudioIndexRoute
  '/assets': typeof AssetsIndexRoute
  '/brand-analysis': typeof BrandAnalysisIndexRoute
  '/canvas': typeof CanvasIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/admin/template/add': typeof AdminTemplateAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas/$id': typeof CanvasIdRoute
  '/ad-performance/': typeof AdPerformanceIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/agent-studio/': typeof AgentStudioIndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/brand-analysis/': typeof BrandAnalysisIndexRoute
  '/canvas/': typeof CanvasIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/admin/template/add': typeof AdminTemplateAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas/$id'
    | '/ad-performance'
    | '/admin'
    | '/agent-studio'
    | '/assets'
    | '/brand-analysis'
    | '/canvas'
    | '/explore'
    | '/knowledge'
    | '/admin/template/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas/$id'
    | '/ad-performance'
    | '/admin'
    | '/agent-studio'
    | '/assets'
    | '/brand-analysis'
    | '/canvas'
    | '/explore'
    | '/knowledge'
    | '/admin/template/add'
  id:
    | '__root__'
    | '/'
    | '/canvas/$id'
    | '/ad-performance/'
    | '/admin/'
    | '/agent-studio/'
    | '/assets/'
    | '/brand-analysis/'
    | '/canvas/'
    | '/explore/'
    | '/knowledge/'
    | '/admin/template/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasIdRoute: typeof CanvasIdRoute
  AdPerformanceIndexRoute: typeof AdPerformanceIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentStudioIndexRoute: typeof AgentStudioIndexRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  BrandAnalysisIndexRoute: typeof BrandAnalysisIndexRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  AdminTemplateAddRoute: typeof AdminTemplateAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-analysis/': {
      id: '/brand-analysis/'
      path: '/brand-analysis'
      fullPath: '/brand-analysis'
      preLoaderRoute: typeof BrandAnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-studio/': {
      id: '/agent-studio/'
      path: '/agent-studio'
      fullPath: '/agent-studio'
      preLoaderRoute: typeof AgentStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-performance/': {
      id: '/ad-performance/'
      path: '/ad-performance'
      fullPath: '/ad-performance'
      preLoaderRoute: typeof AdPerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$id': {
      id: '/canvas/$id'
      path: '/canvas/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof CanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/template/add': {
      id: '/admin/template/add'
      path: '/admin/template/add'
      fullPath: '/admin/template/add'
      preLoaderRoute: typeof AdminTemplateAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasIdRoute: CanvasIdRoute,
  AdPerformanceIndexRoute: AdPerformanceIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentStudioIndexRoute: AgentStudioIndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  BrandAnalysisIndexRoute: BrandAnalysisIndexRoute,
  CanvasIndexRoute: CanvasIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  AdminTemplateAddRoute: AdminTemplateAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
